apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-clock
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicas.clock }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-clock
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-clock
        app_revision: {{ .Release.Name }}_{{ .Release.Revision }}_clock
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app_revision
                    operator: In
                    values:
                      - {{ .Release.Name }}_{{ .Release.Revision }}_clock
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: clock
          image: getlago/api:v{{ .Values.lago_release }}
          imagePullPolicy: Always
          command: ["./scripts/start.clock.sh"]
          env:
            {{- toYaml .Values.clock.environment | nindent 12 }}
          resources:
            requests:
              memory: {{ .Values.clock.resources.memory }}
              cpu: {{ .Values.clock.resources.cpu }}
