apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front-svc
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.front.port }}
      protocol: TCP
      name: front
  selector:
    app: {{ .Release.Name }}-front
