{{ if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
{{ if .Values.global.ingress.annotations }}
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
{{ end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  tls:
  - hosts:
    - {{ .Values.global.ingress.frontHostname }}
    - {{ .Values.global.ingress.apiHostname }}
    - {{ .Values.global.ingress.minioHostname }}
    secretName: {{ .Release.Name }}-ingress-secret
  rules:
  - host: {{ .Values.global.ingress.frontHostname }}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-front-svc
            port:
              number: {{ .Values.front.service.port }}
  - host: {{ .Values.global.ingress.apiHostname }}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-api-svc
            port:
              number: {{ .Values.api.service.port }}
  - host: {{ .Values.global.ingress.minioHostname }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.minio.service.name }}
            port:
              number: {{ .Values.minio.service.port }}
{{ end }}
