apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicas.worker }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-worker
        app_revision: {{ .Release.Name }}_{{ .Release.Revision }}_worker
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app_revision
                    operator: In
                    values:
                      - {{ .Release.Name }}_{{ .Release.Revision }}_worker
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: worker
          image: getlago/api:v{{ .Values.lago_release }}
          imagePullPolicy: Always
          command: ["./scripts/start.worker.sh"]
          env:
            {{- toYaml .Values.worker.environment | nindent 12 }}
          resources:
            requests:
              memory: {{ .Values.worker.resources.memory }}
              cpu: {{ .Values.worker.resources.cpu }}
