name: Release Charts on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release-on-merge:
    if: >
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Lint Chart - Main chart
        run: helm lint .

      - name: Update Dependencies
        run: helm dependency update .

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Deploy to GitHub Pages
        run: |
          git checkout gh-pages
          git pull origin main --rebase --autostash
          helm repo index . --url https://getlago.github.io/charts
          git add .
          git commit -m "Update Helm repo index after release"
          git push origin gh-pages
