name: Release Charts on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Installer jq
        run: sudo apt-get install jq

      - name: Check 'release' Label
        id: check_release_label
        run: |
          labels='${{ toJSON(github.event.pull_request.labels) }}'
          echo "Labels de la PR : $labels"
          if echo "$labels" | jq -e '.[] | select(.name=="release")' > /dev/null; then
            echo "has_release_label=true" >> $GITHUB_ENV
          else
            echo "has_release_label=false" >> $GITHUB_ENV
          fi

      - name: Lint Chart - Main chart
        if: env.has_release_label == 'true'
        run: helm lint .

      - name: Update Dependencies
        if: env.has_release_label == 'true'
        run: helm dependency update .

      - name: Run chart-releaser
        if: env.has_release_label == 'true'
        uses: helm/chart-releaser-action@v1.6.0
        with:
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Deploy to GitHub Pages
        if: env.has_release_label == 'true'
        run: |
          git checkout gh-pages
          git pull origin main --rebase
          helm repo index . --url https://getlago.github.io/charts
          git add .
          git commit -m "Update Helm repo index after release"
          git push origin gh-pages